title: The Quiet Explorer
description: Saddam's Blog

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
      
social:
    github: saddhussein
    twitter: saddamaddas
    # facebook: brianmaierjr
    email: email.saddamh@gmail.com
    linkedin: saddam-hussein
    #youtube: RickAstleyYT
    #tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
